# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 02:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_userpage_business_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows_count', models.IntegerField(blank=True, default=0)),
                ('followers_count', models.IntegerField(blank=True, default=0)),
                ('total_comment_count', models.IntegerField(blank=True, default=0)),
                ('total_like_count', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
