# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_businessaccountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccountdetails',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
